[package]
name = "pdfgen_bindings"
version = "0.1.1"
authors = ["rimathia <rimathia@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = ">=0.2"

[build_dependencies]
cc = ">=1.0"