[package]
name = "pdfgen_bindings"
version = "0.1.0"
authors = ["rimathia <rimathia@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build_dependencies]
cc = "1.0"